name: deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: triggered-run

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check-out-code
        uses: actions/checkout@v2

      - name: configure-aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: pull-from-s3
        run: |
          aws s3 cp s3://zip-files-sms-automations . --recursive

      - name: terraform-init
        run: |
          terraform init

      - name: terraform-plan
        run: |
          terraform plan -var-file="json_variables.tfvars.json"

      - name: terraform-apply
        run: |
          terraform apply -var-file="json_variables.tfvars.json" -auto-approve
